import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import {
  BadgeCheck,
  FileSearch,
  Loader2,
  Play,
  RotateCcw,
  ShieldAlert,
} from "lucide-react";
import { useWorkspace } from "../state/workspace";
import { PageHeader, Panel, SectionHeading } from "../components/ui/Panel";
import {
  Badge,
  Button,
  EmptyState,
  SkeletonPanel,
  StrengthMeter,
} from "../components/ui/Primitives";
import { Tabs, type TabItem } from "../components/ui/Controls";
import { formatDateTime, formatKpiValue } from "../lib/format";
import {
  evidenceEntryTitle,
  evidenceKind,
  kpiMeta,
  periodChangeLabel,
} from "../lib/labels";
import { severity } from "../lib/severity";
import type { EvidenceEntry, Pack } from "../lib/types";

type PackTab = "kpis" | "signals" | "correlations" | "clusters" | "index";

export default function Evidence() {
  const { system, artifacts, investigation, startInvestigation } =
    useWorkspace();
  const [tab, setTab] = useState<PackTab>("kpis");
  const [visibleEntries, setVisibleEntries] = useState(24);

  const pack = investigation.result?.evidence_pack ?? artifacts?.pack ?? null;

  const grouped = useMemo(() => {
    const entries = pack ? Object.entries(pack.evidence_index) : [];
    const buckets: Record<string, [string, EvidenceEntry][]> = {
      kpis: [],
      anomalies: [],
      correlations: [],
      clusters: [],
      other: [],
    };
    for (const pair of entries) {
      buckets[evidenceKind(pair[1].kind).group].push(pair);
    }
    return buckets;
  }, [pack]);

  if (!system?.artifacts_ready && !system?.analysis_running) {
    return (
      <div>
        <PageHeader eyebrow="Intelligence" title="Evidence" />
        <EmptyState
          icon={<FileSearch size={20} />}
          title="No analysis available"
          body="The evidence pack is generated deterministically with every analysis run. Load data first."
          action={
            <Link to="/data">
              <Button>Open Data Workspace</Button>
            </Link>
          }
        />
      </div>
    );
  }

  const grounding = investigation.result?.grounding_report;
  const confidence = grounding?.valid ? 10 : grounding ? 4 : null;

  const tabItems: TabItem[] = [
    { id: "kpis", label: "KPIs & Movement", count: grouped.kpis.length },
    { id: "signals", label: "Signals", count: grouped.anomalies.length },
    {
      id: "correlations",
      label: "Correlations",
      count: grouped.correlations.length,
    },
    { id: "clusters", label: "Clusters", count: grouped.clusters.length },
    {
      id: "index",
      label: "Full Index",
      count: Object.keys(pack?.evidence_index ?? {}).length,
    },
  ];

  return (
    <div>
      <PageHeader
        eyebrow="Intelligence"
        title="Evidence Workspace"
        description="Every number the product shows is traceable to this deterministic pack. AI narratives run only on your explicit action and never overwrite it."
      />

      {/* DETERMINISTIC EVIDENCE PACK */}
      <Panel className="p-5">
        <SectionHeading
          icon={<BadgeCheck size={15} className="text-accent" aria-hidden />}
          title="Deterministic evidence pack"
          caption={
            system.recovery_context
              ? `Frozen at ${formatDateTime(system.recovery_context.completed_at)} · sensitivity ${system.recovery_context.sensitivity}`
              : "Generated by the last pipeline run."
          }
        />
        {!pack ? (
          <SkeletonPanel lines={4} />
        ) : (
          <>
            <Tabs
              ariaLabel="Evidence sections"
              items={tabItems}
              active={tab}
              onChange={(id) => {
                setTab(id as PackTab);
                setVisibleEntries(24);
              }}
            />
            <div className="pt-4">
              {tab === "kpis" && <KpisTab buckets={grouped} pack={pack} />}
              {tab === "signals" && <SignalsTab buckets={grouped} />}
              {tab === "correlations" && (
                <EntriesGrid
                  pairs={grouped.correlations}
                  emptyText="No correlation evidence in this run."
                />
              )}
              {tab === "clusters" && (
                <EntriesGrid
                  pairs={grouped.clusters}
                  emptyText="No signal clusters were formed in this run."
                />
              )}
              {tab === "index" && (
                <EntriesGrid
                  pairs={[
                    ...grouped.kpis,
                    ...grouped.anomalies,
                    ...grouped.correlations,
                    ...grouped.clusters,
                    ...grouped.other,
                  ]}
                  pageSize={visibleEntries}
                  onShowMore={() =>
                    setVisibleEntries((n) => n + 24)
                  }
                  emptyText="No evidence recorded."
                />
              )}
            </div>
          </>
        )}
      </Panel>

      {/* AI INVESTIGATION CONSOLE */}
      <Panel className="mt-6 p-5">
        <SectionHeading
          icon={<BadgeCheck size={15} className="text-accent" aria-hidden />}
          title="AI investigation"
          caption="AI-assisted investigation reads the frozen evidence pack and returns a grounded narrative with citations. Deterministic evidence above is never modified."
        />
        <InvestigationConsole
          aiAvailable={system.ai_available === true}
          status={investigation.status}
          error={investigation.error}
          onRun={() => void startInvestigation()}
        />
        {system.ai_available && (
          <p className="mt-2 text-[10px] uppercase tracking-wider text-text-muted">
            Model: {system.gemini_model}
          </p>
        )}

        {grounding && (
          <div className="mt-4 grid gap-3 rounded-xl border border-line bg-white/[0.02] p-4 md:grid-cols-[220px_1fr]">
            <div>
              <p className="text-[10px] font-bold uppercase tracking-[0.18em] text-text-muted">
                Grounding verification
              </p>
              <div className="mt-2">
                <Badge tone={grounding.valid ? "ok" : "danger"}>
                  {grounding.valid ? "All citations resolved" : "Verification issues"}
                </Badge>
              </div>
              {confidence !== null && (
                <div className="mt-3 max-w-[180px]">
                  <StrengthMeter
                    value={confidence}
                    maximum={10}
                    label="Grounding strength"
                  />
                </div>
              )}
            </div>
            <ul className="space-y-1 text-xs leading-relaxed text-text-2">
              {(grounding.citation_errors ?? []).map((error, i) => (
                <li key={`c${i}`}>· citation: {error}</li>
              ))}
              {(grounding.numeric_errors ?? []).map((error, i) => (
                <li key={`n${i}`}>· numeric: {error}</li>
              ))}
              {(grounding.causation_errors ?? []).map((error, i) => (
                <li key={`x${i}`}>· causation: {error}</li>
              ))}
              {(grounding.unsupported_claims ?? []).map((claim, i) => (
                <li key={`u${i}`}>· unsupported: {claim}</li>
              ))}
              {grounding.valid && (
                <li>
                  Every claim cites a deterministic evidence reference; all
                  numbers were verified against the frozen pack before display.
                </li>
              )}
            </ul>
          </div>
        )}
      </Panel>

      {/* NARRATIVE REPORT */}
      {investigation.result && (
        <Panel className="mt-4 p-5">
          <SectionHeading
            title="AI investigation report"
            caption="AI-generated · grounded in the evidence pack · clearly separated from deterministic output."
          />
          <p className="text-sm leading-relaxed text-text-2">
            {investigation.result.narrative.executive_summary}
          </p>
          <div className="mt-4 grid gap-6 lg:grid-cols-2">
            <NarrativeList
              heading="Key findings"
              items={investigation.result.narrative.key_findings}
            />
            <NarrativeList
              heading="Operational interpretation"
              items={investigation.result.narrative.operational_interpretation}
            />
          </div>
          {investigation.result.hypotheses?.length > 0 && (
            <div className="mt-6">
              <h3 className="text-[10px] font-bold uppercase tracking-[0.18em] text-text-muted">
                Hypotheses for human review
              </h3>
              <ul className="mt-2 space-y-2">
                {investigation.result.hypotheses.map((h, i) => (
                  <li
                    key={`h${i}`}
                    className="rounded-lg border border-line bg-white/[0.02] px-3 py-2.5"
                  >
                    <p className="text-sm text-text">{h.hypothesis}</p>
                    <p className="num mt-1 text-[11px] text-text-muted">
                      confidence {(h.confidence * 100).toFixed(0)}%
                      {h.factor ? ` · factor: ${h.factor}` : ""}
                      {h.evidence_ids.length > 0 &&
                        ` · refs ${h.evidence_ids.join(", ")}`}
                    </p>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </Panel>
      )}
    </div>
  );
}

// --- Investigation console -----------------------------------------------------------------------------

function InvestigationConsole({
  aiAvailable,
  status,
  error,
  onRun,
}: {
  aiAvailable: boolean;
  status: string;
  error: string | null;
  onRun: () => void;
}) {
  const [elapsed, setElapsed] = useState<number | null>(null);
  const [stageIndex, setStageIndex] = useState(0);

  useEffect(() => {
    if (status !== "running") {
      setElapsed(null);
      setStageIndex(0);
      return;
    }
    const started = Date.now();
    setElapsed(0);
    const timer = window.setInterval(
      () => setElapsed(Math.floor((Date.now() - started) / 1000)),
      1000,
    );
    return () => window.clearInterval(timer);
  }, [status]);

  // Descriptive captions of the investigation's real phases — advanced by
  // elapsed time only as presentation; status itself comes from polling.
  useEffect(() => {
    if (status !== "running") return;
    const timer = window.setInterval(
      () => setStageIndex((i) => Math.min(i + 1, INVESTIGATION_STAGES.length - 1)),
      25_000,
    );
    return () => window.clearInterval(timer);
  }, [status]);

  if (!aiAvailable) {
    return (
      <p className="flex items-center gap-2 rounded-lg border border-warn/30 bg-warn/[0.08] px-3 py-2.5 text-sm text-warn">
        <ShieldAlert size={15} aria-hidden />
        AI investigation is not configured — deterministic evidence remains fully
        available above.
      </p>
    );
  }

  return (
    <div className="flex flex-wrap items-center gap-3">
      {status === "running" ? (
        <div className="flex flex-col gap-1">
          <span className="inline-flex items-center gap-2 text-sm font-semibold text-accent">
            <Loader2 size={15} className="animate-spin" aria-hidden />
            AI investigation running
            {elapsed !== null && (
              <span className="num text-xs text-text-muted">{elapsed}s</span>
            )}
          </span>
          <span aria-live="polite" className="text-xs text-text-2">
            {INVESTIGATION_STAGES[stageIndex]}
          </span>
        </div>
      ) : (
        <Button onClick={onRun}>
          {status === "error" || status === "complete" ? (
            <RotateCcw size={14} />
          ) : (
            <Play size={14} />
          )}
          {status === "error"
            ? "Retry Investigation"
            : status === "complete"
              ? "Re-run Investigation"
              : "Run AI Investigation"}
        </Button>
      )}
      {status === "complete" && <Badge tone="ok">Grounded narrative ready</Badge>}
      {status !== "running" && status !== "complete" && !error && (
        <span className="text-xs text-text-muted">
          Typical duration: under a minute.
        </span>
      )}
      {error && (
        <p role="alert" className="w-full text-sm text-danger">
          {error}
        </p>
      )}
    </div>
  );
}

const INVESTIGATION_STAGES = [
  "Preparing the frozen evidence pack…",
  "Analyzing operational signals…",
  "Generating grounded findings…",
  "Finalizing recommendations…",
];

// --- Pack tabs ------------------------------------------------------------------------------------------

type Buckets = Record<string, [string, EvidenceEntry][]>;

function KpisTab({
  buckets,
  pack,
}: {
  buckets: Buckets;
  pack: Pack;
}) {
  return (
    <div className="space-y-6">
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
        {Object.entries(pack.kpis).map(([key, value]) => {
          const meta = kpiMeta(key);
          return (
            <div
              key={key}
              title={meta.description}
              className="rounded-xl border border-line bg-white/[0.02] p-3.5"
            >
              <p className="text-[10px] font-bold uppercase tracking-[0.18em] text-text-muted">
                {meta.title}
              </p>
              <p className="num mt-1 text-lg font-bold text-text">
                {formatKpiValue(value, meta.kind)}
              </p>
            </div>
          );
        })}
      </div>

      {Object.keys(pack.period_comparison?.changes_pct ?? {}).length > 0 && (
        <div>
          <h3 className="text-[10px] font-bold uppercase tracking-[0.18em] text-text-muted">
            Period-over-period movement
          </h3>
          <div className="mt-2 flex flex-wrap gap-2">
            {Object.entries(pack.period_comparison.changes_pct).map(
              ([key, pct]) => (
                <span
                  key={key}
                  className="flex items-center gap-2 rounded-lg border border-line px-3 py-1.5 text-xs"
                >
                  <span className="text-text-2">{periodChangeLabel(key)}</span>
                  {pct === null ? (
                    <span className="num text-text-muted">—</span>
                  ) : (
                    <span
                      className={`num font-bold ${Number(pct) >= 0 ? "text-ok" : "text-danger"}`}
                    >
                      {Number(pct) >= 0 ? "+" : ""}
                      {Number(pct).toFixed(1)}%
                    </span>
                  )}
                </span>
              ),
            )}
          </div>
        </div>
      )}

      <EntriesGrid pairs={buckets.kpis.filter(([, e]) => e.kind === "performer")} />
    </div>
  );
}

function SignalsTab({ buckets }: { buckets: Buckets }) {
  const anomalies = artifactsAnomalies(buckets);
  if (anomalies.length === 0) {
    return (
      <p className="py-6 text-center text-sm text-text-2">
        No anomaly evidence recorded in this run.
      </p>
    );
  }
  return (
    <ul className="divide-y divide-line">
      {anomalies.map(([id, entry]) => (
        <li
          key={id}
          className="flex flex-wrap items-center justify-between gap-2 py-2.5 first:pt-0 last:pb-0"
        >
          <span className="text-sm font-medium text-text">
            {evidenceEntryTitle(entry)}
          </span>
          <span className="flex items-center gap-2">
            {typeof entry.deviation_pct === "number" && (
              <span className="num text-xs font-bold text-danger">
                +{Math.abs(entry.deviation_pct).toFixed(1)}% vs baseline
              </span>
            )}
            <RefChip id={id} />
          </span>
        </li>
      ))}
    </ul>
  );
}

/** Pull severity-sorted anomaly evidence ids for the signals tab. */
function artifactsAnomalies(buckets: Buckets): [string, EvidenceEntry][] {
  return [...buckets.anomalies].sort(
    (a, b) =>
      severity(String(b[1].severity ?? "")).weight -
      severity(String(a[1].severity ?? "")).weight,
  );
}

function EntriesGrid({
  pairs,
  pageSize,
  onShowMore,
  emptyText = "No entries.",
}: {
  pairs: [string, EvidenceEntry][];
  pageSize?: number;
  onShowMore?: () => void;
  emptyText?: string;
}) {
  if (pairs.length === 0) {
    return <p className="py-6 text-center text-sm text-text-2">{emptyText}</p>;
  }
  const shown = pageSize ? pairs.slice(0, pageSize) : pairs;
  return (
    <div>
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
        {shown.map(([id, entry]) => {
          const kind = evidenceKind(entry.kind);
          return (
            <div
              key={id}
              className="rounded-xl border border-line bg-white/[0.02] p-3.5"
            >
              <div className="flex items-start justify-between gap-2">
                <p className="text-sm font-semibold leading-snug text-text">
                  {evidenceEntryTitle(entry)}
                </p>
                <Badge tone="muted" withIcon={false}>
                  {kind.label}
                </Badge>
              </div>
              {entry.value !== undefined && entry.value !== null && (
                <p className="num mt-1 text-sm text-text-2">
                  {typeof entry.value === "number"
                    ? entry.value.toLocaleString()
                    : String(entry.value)}
                </p>
              )}
              {typeof entry.deviation_pct === "number" && (
                <p className="num mt-0.5 text-xs font-bold text-danger">
                  +{Math.abs(entry.deviation_pct).toFixed(1)}% vs baseline
                </p>
              )}
              <RefChip id={id} />
            </div>
          );
        })}
      </div>
      {pageSize && pairs.length > shown.length && (
        <div className="mt-4 text-center">
          <Button variant="ghost" onClick={onShowMore}>
            Show more ({pairs.length - shown.length} remaining)
          </Button>
        </div>
      )}
    </div>
  );
}

/** Small citation reference — metadata, not a label. */
function RefChip({ id }: { id: string }) {
  return (
    <span
      title={`Citation reference ${id}`}
      className="num mt-2 inline-block rounded border border-line px-1.5 py-0.5 text-[10px] text-text-muted"
    >
      ref {id}
    </span>
  );
}

// --- Narrative -------------------------------------------------------------------------------------------

function NarrativeList({
  heading,
  items,
}: {
  heading: string;
  items: { claim: string; evidence_ids: string[] }[];
}) {
  return (
    <section aria-label={heading}>
      <h3 className="text-[10px] font-bold uppercase tracking-[0.18em] text-text-muted">
        {heading}
      </h3>
      <ul className="mt-2 space-y-2.5">
        {items.map((item, index) => (
          <li key={index} className="border-l-2 border-accent/50 pl-3">
            <p className="text-sm leading-relaxed text-text-2">{item.claim}</p>
            {item.evidence_ids.length > 0 && (
              <p className="num mt-1 text-[11px] text-accent">
                [{item.evidence_ids.join(", ")}]
              </p>
            )}
          </li>
        ))}
      </ul>
    </section>
  );
}
